### ISSUE TITLE
Version 0.3.0 break lib.

### ISSUE THREAD

**Issue by JoaoOtavioS** [logtail/logtail-js#46]
node_modules/@logtail/node/dist/cjs/context.js:75

if (argv[i].startsWith('-')) {
                    ^
TypeError: argv[i].startsWith is not a function
    at mainFileName (?/node_modules/@logtail/node/dist/cjs/context.js:75:21)
    at Object.<anonymous> (?/node_modules/@logtail/node/dist/cjs/context.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (?/node_modules/@logtail/node/dist/cjs/node.js:10:19)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)

This recheck broke the lib in every use I was able to test it on.

**Comment by JoaoOtavioS** [comment]
![image](https://user-images.githubusercontent.com/41020839/221321009-9f701570-e8c9-4699-b284-139b4ddf679a.png)

**Comment by curusarn** [comment]
Hi @JoaoOtavioS,

Thanks for reporting this.

I did not manage to reproduce the issue.
But based on the error you have shared I have just released `v0.3.1` with a fix.

Could you update and let me know if it works for you? 🙏 
Please feel free to reopen the issue if problem persists.
