### ISSUE TITLE
Unauthorized error on logs

### ISSUE THREAD

**Issue by tangb** [logtail/logtail-js#55]
Hi

Since I migrated from logzio to logtail, I encounter a lot of log like this:
```
2023-03-25T11:37:50+01:00 Error: Unauthorized
2023-03-25T11:37:50+01:00 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-03-25T11:37:50+01:00 at Node.sync [as _sync] (/home/bas/app_f4b3548e-31fe-46b4-8dfc-502f72a8b749/node_modules/@logtail/node/dist/cjs/node.js:28:19)
2023-03-25T11:37:50+01:00 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-03-25T11:37:50+01:00 Error: Unauthorized
2023-03-25T11:37:50+01:00 at async handler (/home/bas/app_f4b3548e-31fe-46b4-8dfc-502f72a8b749/node_modules/@logtail/tools/dist/cjs/throttle.js:34:37)
2023-03-25T11:37:50+01:00 at Node.sync [as _sync] (/home/bas/app_f4b3548e-31fe-46b4-8dfc-502f72a8b749/node_modules/@logtail/node/dist/cjs/node.js:28:19)
2023-03-25T11:37:50+01:00 at async handler (/home/bas/app_f4b3548e-31fe-46b4-8dfc-502f72a8b749/node_modules/@logtail/tools/dist/cjs/throttle.js:34:37
```

The stack seems to say it's a problem from logtail library and it match the apparition of this kind of messages and my migration to logtail.
Despite this problem it seems I got all my logs in the logtail dashboard.

Maybe v0.3.3 fix the problem but I can test it due to peer dep issue (I created another issue)

Thank you for your support ;-)

**Comment by JoaoOtavioS** [comment]
same problem in 0.3.3

**Comment by tangb** [comment]
Hi

It seems to be resolved

Thank you very much :)

**Comment by pesterhazy** [comment]
When I encountered this issue on a new source, I had to explicitly set the endpoint

**Comment by Souvlaki42** [comment]
I encountered the same issue in the latest issue when trying to connect it with winston in my discord.js project. Any ideas how to fix it?

**Comment by sebastiansas1** [comment]
So apparently now we need to also set the `INGESTING_HOST` which was not required before. 
![Image](https://github.com/user-attachments/assets/79ab7aed-09de-4be9-bcd8-753c55bd44ea)

Would have been helpful to have some kind of reason explaining the issue, instead of a plain "Unauthorized" error.
